import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kanban App</title>
        <meta
          name="description"
          content="Generated by create-t3-app"
          key="description"
        />
        <link rel="icon" href="/icon.png" key="favicon" />
      </Head>
      <h1 className="text-4xl font-bold">Welcome to Kanban App!</h1>
    </>
  );
}
